
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { useAuthStore } from "./store/useAuthStore";
import Footer from "./components/Footer";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
  
    <html lang="en">
      
    <head>
    <script type="text/javascript" src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>


     



    </head>

      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
          <Toaster position="top-center" />
        {children}

      </body>
     
    </html>

  );
}
